import type { Metadata, Viewport } from "next";
import { Crimson_Pro, Inter } from "next/font/google";
import "./globals.css";
import ServiceWorker from "@/components/ServiceWorker";

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  variable: "--font-crimson-pro",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hymnal",
  description:
    "A Collection of Hymns and Sacred Songs — Old German Baptist Brethren Church, 32nd Edition.",
  manifest: "/manifest.json",
  applicationName: "Hymnal",
  appleWebApp: {
    capable: true,
    title: "Hymnal",
    statusBarStyle: "default",
    // iOS shows a blank white sheet on PWA launch unless handed one of these
    // per device class. Generated by scripts/make-launch-art.mjs.
    startupImage: [
      { url: "/splash/750x1334.png", media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" },
      { url: "/splash/828x1792.png", media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" },
      { url: "/splash/1125x2436.png", media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" },
      { url: "/splash/1170x2532.png", media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" },
      { url: "/splash/1179x2556.png", media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)" },
      { url: "/splash/1206x2622.png", media: "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3)" },
      { url: "/splash/1290x2796.png", media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)" },
      { url: "/splash/1320x2868.png", media: "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3)" },
    ],
  },
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: { url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fdfbf7" },
    { media: "(prefers-color-scheme: dark)", color: "#16130f" },
  ],
};

/**
 * Applies the stored theme and text size before first paint. Without this the
 * page renders light and then flips, which is exactly the moment a dark-mode
 * user is looking at it.
 */
const THEME_SCRIPT = `
(function () {
  try {
    var saved = JSON.parse(localStorage.getItem("hymnal") || "{}").state || {};
    var theme = saved.theme || "system";
    var dark = theme === "dark" || (theme === "system" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);
    document.documentElement.dataset.theme = dark ? "dark" : "light";
    var scale = { s: 0.9, m: 1, l: 1.15, xl: 1.32 }[saved.textSize || "m"];
    document.documentElement.style.setProperty("--type-scale", String(scale));
  } catch (e) {}
})();
`;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${crimsonPro.variable} ${inter.variable}`} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
        {/* Fall Studios analytics. Cookieless; skips localhost. data-site must
            match the slug in fall-studios/lib/projects.ts. */}
        <script defer src="https://fall-studios.vercel.app/t.js" data-site="hymnal" />
      </head>
      <body>
        {children}
        <ServiceWorker />
      </body>
    </html>
  );
}
